from __future__ import annotations


KEYCODES: dict[str, int] = {
    "none": 0x00,
    "a": 0x04,
    "b": 0x05,
    "c": 0x06,
    "d": 0x07,
    "e": 0x08,
    "f": 0x09,
    "g": 0x0A,
    "h": 0x0B,
    "i": 0x0C,
    "j": 0x0D,
    "k": 0x0E,
    "l": 0x0F,
    "m": 0x10,
    "n": 0x11,
    "o": 0x12,
    "p": 0x13,
    "q": 0x14,
    "r": 0x15,
    "s": 0x16,
    "t": 0x17,
    "u": 0x18,
    "v": 0x19,
    "w": 0x1A,
    "x": 0x1B,
    "y": 0x1C,
    "z": 0x1D,
    "1": 0x1E,
    "num1": 0x1E,
    "num-1": 0x1E,
    "2": 0x1F,
    "num2": 0x1F,
    "num-2": 0x1F,
    "3": 0x20,
    "num3": 0x20,
    "num-3": 0x20,
    "4": 0x21,
    "num4": 0x21,
    "num-4": 0x21,
    "5": 0x22,
    "num5": 0x22,
    "num-5": 0x22,
    "6": 0x23,
    "num6": 0x23,
    "num-6": 0x23,
    "7": 0x24,
    "num7": 0x24,
    "num-7": 0x24,
    "8": 0x25,
    "num8": 0x25,
    "num-8": 0x25,
    "9": 0x26,
    "num9": 0x26,
    "num-9": 0x26,
    "0": 0x27,
    "num0": 0x27,
    "num-0": 0x27,
    "enter": 0x28,
    "return": 0x28,
    "esc": 0x29,
    "escape": 0x29,
    "backspace": 0x2A,
    "tab": 0x2B,
    "space": 0x2C,
    "-": 0x2D,
    "minus": 0x2D,
    "subund": 0x2D,
    "sub-und": 0x2D,
    "sub-underscore": 0x2D,
    "=": 0x2E,
    "equal": 0x2E,
    "eqadd": 0x2E,
    "eq-add": 0x2E,
    "equal-plus": 0x2E,
    "[": 0x2F,
    "leftbracket": 0x2F,
    "left-bracket": 0x2F,
    "lz-bracket": 0x2F,
    "]": 0x30,
    "rightbracket": 0x30,
    "right-bracket": 0x30,
    "rz-bracket": 0x30,
    "\\": 0x31,
    "backslash": 0x31,
    "nonushash": 0x32,
    ";": 0x33,
    "semicolon": 0x33,
    "sem-dwu": 0x33,
    "semdwu": 0x33,
    "'": 0x34,
    "quote": 0x34,
    "sd-quo": 0x34,
    "sdquo": 0x34,
    "`": 0x35,
    "grave": 0x35,
    "tilde": 0x35,
    "dewen1": 0x35,
    "de-wen1": 0x35,
    ",": 0x36,
    "comma": 0x36,
    "com-lang-bra": 0x36,
    "comlangbra": 0x36,
    ".": 0x37,
    "dot": 0x37,
    "period": 0x37,
    "full-rang-bra": 0x37,
    "fullrangbra": 0x37,
    "/": 0x38,
    "slash": 0x38,
    "slashw": 0x38,
    "slash-w": 0x38,
    "capslock": 0x39,
    "caps-lock": 0x39,
    "f1": 0x3A,
    "f2": 0x3B,
    "f3": 0x3C,
    "f4": 0x3D,
    "f5": 0x3E,
    "f6": 0x3F,
    "f7": 0x40,
    "f8": 0x41,
    "f9": 0x42,
    "f10": 0x43,
    "f11": 0x44,
    "f12": 0x45,
    "printscreen": 0x46,
    "print-screen": 0x46,
    "prtsc": 0x46,
    "prtscsysrq": 0x46,
    "prt-sc-sys-rq": 0x46,
    "scrolllock": 0x47,
    "scroll-lock": 0x47,
    "scrlock": 0x47,
    "scr-lock": 0x47,
    "pause": 0x48,
    "insert": 0x49,
    "home": 0x4A,
    "pageup": 0x4B,
    "delete": 0x4C,
    "del": 0x4C,
    "end": 0x4D,
    "pagedown": 0x4E,
    "right": 0x4F,
    "arrowright": 0x4F,
    "arrow-right": 0x4F,
    "arrowsright": 0x4F,
    "arrows-right": 0x4F,
    "left": 0x50,
    "arrowleft": 0x50,
    "arrow-left": 0x50,
    "arrowsleft": 0x50,
    "arrows-left": 0x50,
    "down": 0x51,
    "arrowdown": 0x51,
    "arrow-down": 0x51,
    "arrowsdown": 0x51,
    "arrows-down": 0x51,
    "up": 0x52,
    "arrowup": 0x52,
    "arrow-up": 0x52,
    "arrowsup": 0x52,
    "arrows-up": 0x52,
    "numlock": 0x53,
    "num-lock": 0x53,
    "kp/": 0x54,
    "kpdiv": 0x54,
    "kp-div": 0x54,
    "numpad/": 0x54,
    "numpad-div": 0x54,
    "div": 0x54,
    "kp*": 0x55,
    "kpmul": 0x55,
    "kp-mul": 0x55,
    "numpad*": 0x55,
    "numpad-mul": 0x55,
    "mul": 0x55,
    "kp-": 0x56,
    "kpsub": 0x56,
    "kp-sub": 0x56,
    "numpad-": 0x56,
    "numpad-sub": 0x56,
    "sub": 0x56,
    "kp+": 0x57,
    "kpadd": 0x57,
    "kp-add": 0x57,
    "numpad+": 0x57,
    "numpad-add": 0x57,
    "add": 0x57,
    "kpenter": 0x58,
    "kp-enter": 0x58,
    "numpad-enter": 0x58,
    "enter-2": 0x58,
    "kp1": 0x59,
    "kp-1": 0x59,
    "numpad1": 0x59,
    "numpad-1": 0x59,
    "m-num1": 0x59,
    "kp2": 0x5A,
    "kp-2": 0x5A,
    "numpad2": 0x5A,
    "numpad-2": 0x5A,
    "m-num2": 0x5A,
    "kp3": 0x5B,
    "kp-3": 0x5B,
    "numpad3": 0x5B,
    "numpad-3": 0x5B,
    "m-num3": 0x5B,
    "kp4": 0x5C,
    "kp-4": 0x5C,
    "numpad4": 0x5C,
    "numpad-4": 0x5C,
    "m-num4": 0x5C,
    "kp5": 0x5D,
    "kp-5": 0x5D,
    "numpad5": 0x5D,
    "numpad-5": 0x5D,
    "m-num5": 0x5D,
    "kp6": 0x5E,
    "kp-6": 0x5E,
    "numpad6": 0x5E,
    "numpad-6": 0x5E,
    "m-num6": 0x5E,
    "kp7": 0x5F,
    "kp-7": 0x5F,
    "numpad7": 0x5F,
    "numpad-7": 0x5F,
    "m-num7": 0x5F,
    "kp8": 0x60,
    "kp-8": 0x60,
    "numpad8": 0x60,
    "numpad-8": 0x60,
    "m-num8": 0x60,
    "kp9": 0x61,
    "kp-9": 0x61,
    "numpad9": 0x61,
    "numpad-9": 0x61,
    "m-num9": 0x61,
    "kp0": 0x62,
    "kp-0": 0x62,
    "numpad0": 0x62,
    "numpad-0": 0x62,
    "m-num0": 0x62,
    "kp.": 0x63,
    "kp-dot": 0x63,
    "numpad.": 0x63,
    "numpad-dot": 0x63,
    "m-num-dot": 0x63,
    "nonusbackslash": 0x64,
    "application": 0x65,
    "app": 0x65,
    "menu": 0x65,
    "power": 0x66,
    "kpequal": 0x67,
    "f13": 0x68,
    "f14": 0x69,
    "f15": 0x6A,
    "f16": 0x6B,
    "f17": 0x6C,
    "f18": 0x6D,
    "f19": 0x6E,
    "f20": 0x6F,
    "f21": 0x70,
    "f22": 0x71,
    "f23": 0x72,
    "f24": 0x73,
    "lctrl": 0xE0,
    "ctrl": 0xE0,
    "leftctrl": 0xE0,
    "left-ctrl": 0xE0,
    "lshift": 0xE1,
    "shift": 0xE1,
    "leftshift": 0xE1,
    "left-shift": 0xE1,
    "lalt": 0xE2,
    "alt": 0xE2,
    "leftalt": 0xE2,
    "left-alt": 0xE2,
    "option": 0xE2,
    "lgui": 0xE3,
    "leftgui": 0xE3,
    "left-gui": 0xE3,
    "cmd": 0xE3,
    "command": 0xE3,
    "win": 0xE3,
    "rctrl": 0xE4,
    "rightctrl": 0xE4,
    "right-ctrl": 0xE4,
    "rshift": 0xE5,
    "rightshift": 0xE5,
    "right-shift": 0xE5,
    "ralt": 0xE6,
    "rightalt": 0xE6,
    "right-alt": 0xE6,
    "roption": 0xE6,
    "rgui": 0xE7,
    "rightgui": 0xE7,
    "right-gui": 0xE7,
    "rcmd": 0xE7,
    "null": 0x00,
}

MEDIA_USAGES: dict[str, int] = {
    "fast-forward": 0xB3,
    "ff": 0xB3,
    "rewind": 0xB4,
    "play-pause": 0xCD,
    "playpause": 0xCD,
    "play": 0xCD,
    "pause": 0xCD,
    "previous-track": 0xB6,
    "prev-track": 0xB6,
    "previous": 0xB6,
    "prev": 0xB6,
    "next-track": 0xB5,
    "next": 0xB5,
    "stop": 0xB7,
    "eject": 0xB8,
    "mute": 0xE2,
    "volume-up": 0xE9,
    "vol-up": 0xE9,
    "volume+": 0xE9,
    "volume-down": 0xEA,
    "vol-down": 0xEA,
    "volume-": 0xEA,
    "brightness-up": 0x6F,
    "brightness+": 0x6F,
    "brightness-down": 0x70,
    "brightness-": 0x70,
    "display-brightness-up": 0x6F,
    "display-brightness-down": 0x70,
    "keyboard-brightness-up": 0x79,
    "keyboard-brightness-down": 0x7A,
    "consumer-control-config": 0x0183,
    "media-select": 0x0183,
    "multimedia": 0x0183,
    "email": 0x018A,
    "mail": 0x018A,
    "calculator": 0x0192,
    "calc": 0x0192,
    "my-computer": 0x0194,
    "local-machine-browser": 0x0194,
    "internet-browser": 0x0196,
    "browser": 0x0196,
    "bass-up": 0x0152,
    "bass-down": 0x0153,
    "treble-up": 0x0154,
    "treble-down": 0x0155,
    "browser-search": 0x0221,
    "search": 0x0221,
    "browser-home": 0x0223,
    "home-page": 0x0223,
    "browser-back": 0x0224,
    "browser-forward": 0x0225,
    "browser-refresh": 0x0227,
    "refresh": 0x0227,
    "vendor-0x0123": 0x0123,
}

MODIFIER_TOKENS: dict[str, int] = {
    "ctrl": 0xF1,
    "control": 0xF1,
    "lctrl": 0xF1,
    "leftctrl": 0xF1,
    "shift": 0xF2,
    "lshift": 0xF2,
    "leftshift": 0xF2,
    "alt": 0xF3,
    "option": 0xF3,
    "lalt": 0xF3,
    "leftalt": 0xF3,
    "cmd": 0xF4,
    "command": 0xF4,
    "gui": 0xF4,
    "win": 0xF4,
    "lgui": 0xF4,
    "leftgui": 0xF4,
    "rctrl": 0xF5,
    "rightctrl": 0xF5,
    "rshift": 0xF6,
    "rightshift": 0xF6,
    "ralt": 0xF7,
    "rightalt": 0xF7,
    "roption": 0xF7,
    "rcmd": 0xF8,
    "rightcmd": 0xF8,
    "rgui": 0xF8,
    "rightgui": 0xF8,
}

PREFERRED_MODIFIER_TOKEN_NAMES: dict[int, str] = {
    0xF1: "ctrl",
    0xF2: "shift",
    0xF3: "alt",
    0xF4: "cmd",
    0xF5: "rctrl",
    0xF6: "rshift",
    0xF7: "ralt",
    0xF8: "rcmd",
}

CANONICAL_NAMES: tuple[str, ...] = (
    "none",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "enter",
    "esc",
    "backspace",
    "tab",
    "space",
    "minus",
    "equal",
    "leftbracket",
    "rightbracket",
    "backslash",
    "semicolon",
    "quote",
    "grave",
    "comma",
    "period",
    "slash",
    "capslock",
    "f1",
    "f2",
    "f3",
    "f4",
    "f5",
    "f6",
    "f7",
    "f8",
    "f9",
    "f10",
    "f11",
    "f12",
    "printscreen",
    "scrolllock",
    "pause",
    "insert",
    "home",
    "pageup",
    "delete",
    "end",
    "pagedown",
    "right",
    "left",
    "down",
    "up",
    "numlock",
    "kp/",
    "kp*",
    "kp-",
    "kp+",
    "kpenter",
    "kp1",
    "kp2",
    "kp3",
    "kp4",
    "kp5",
    "kp6",
    "kp7",
    "kp8",
    "kp9",
    "kp0",
    "kp.",
    "application",
    "lctrl",
    "lshift",
    "lalt",
    "lgui",
    "rctrl",
    "rshift",
    "ralt",
    "rgui",
)

VENDOR_BASIC_KEY_ALIASES: tuple[tuple[str, str], ...] = (
    ("Ctrl", "ctrl"),
    ("Shift", "shift"),
    ("Win", "win"),
    ("Alt", "alt"),
    ("Space", "space"),
    ("ADD", "add"),
    ("SUB", "sub"),
    ("MUL", "mul"),
    ("DIV", "div"),
    ("DeWen1", "dewen1"),
    ("NUM1", "num1"),
    ("NUM2", "num2"),
    ("NUM3", "num3"),
    ("NUM4", "num4"),
    ("NUM5", "num5"),
    ("NUM6", "num6"),
    ("NUM7", "num7"),
    ("NUM8", "num8"),
    ("NUM9", "num9"),
    ("NUM0", "num0"),
    ("SubUnd", "subund"),
    ("EqAdd", "eqadd"),
    ("ArrowsUp", "arrowsup"),
    ("A", "a"),
    ("B", "b"),
    ("C", "c"),
    ("D", "d"),
    ("E", "e"),
    ("F", "f"),
    ("G", "g"),
    ("H", "h"),
    ("I", "i"),
    ("J", "j"),
    ("K", "k"),
    ("L", "l"),
    ("M", "m"),
    ("N", "n"),
    ("O", "o"),
    ("P", "p"),
    ("Q", "q"),
    ("R", "r"),
    ("S", "s"),
    ("T", "t"),
    ("U", "u"),
    ("V", "v"),
    ("W", "w"),
    ("X", "x"),
    ("Y", "y"),
    ("Z", "z"),
    ("App", "app"),
    ("ArrowsDown", "arrowsdown"),
    ("TAB", "tab"),
    ("CapsLock", "capslock"),
    ("Enter", "enter"),
    ("LZ_bracket", "lz-bracket"),
    ("RZ_bracket", "rz-bracket"),
    ("backslash", "backslash"),
    ("SemDwu", "semdwu"),
    ("Sd_Quo", "sd-quo"),
    ("ComLAngBra", "com-lang-bra"),
    ("FullRAngBra", "full-rang-bra"),
    ("SlashW", "slashw"),
    ("ESC", "esc"),
    ("F1", "f1"),
    ("F2", "f2"),
    ("F3", "f3"),
    ("F4", "f4"),
    ("F5", "f5"),
    ("F6", "f6"),
    ("F7", "f7"),
    ("F8", "f8"),
    ("F9", "f9"),
    ("F10", "f10"),
    ("F11", "f11"),
    ("F12", "f12"),
    ("ArrowsLeft", "arrowsleft"),
    ("ScrLock", "scrlock"),
    ("PrtScSysRq", "prtscsysrq"),
    ("Insert", "insert"),
    ("End", "end"),
    ("Delete", "delete"),
    ("Home", "home"),
    ("PageUp", "pageup"),
    ("PageDown", "pagedown"),
    ("Pause", "pause"),
    ("Backspace", "backspace"),
    ("ArrowsRight", "arrowsright"),
    ("NumLock", "numlock"),
    ("Enter_2", "enter-2"),
    ("M_NUM1", "m-num1"),
    ("M_NUM2", "m-num2"),
    ("M_NUM3", "m-num3"),
    ("M_NUM4", "m-num4"),
    ("M_NUM5", "m-num5"),
    ("M_NUM6", "m-num6"),
    ("M_NUM7", "m-num7"),
    ("M_NUM8", "m-num8"),
    ("M_NUM9", "m-num9"),
    ("M_NUM0", "m-num0"),
    ("M_NUM_Dot", "m-num-dot"),
    ("NULL", "null"),
)


def parse_byte_name(value: str, table: dict[str, int], kind: str) -> int:
    normalized = value.strip().lower().replace("_", "-")
    if not normalized:
        raise ValueError(f"empty {kind}")
    if normalized in table:
        return table[normalized]
    try:
        number = int(normalized, 0)
    except ValueError as exc:
        raise ValueError(f"unknown {kind} {value!r}") from exc
    if not 0 <= number <= 0xFF:
        raise ValueError(f"{kind} out of byte range: {value!r}")
    return number


def parse_keycode(value: str) -> int:
    normalized = value.strip().lower().replace("_", "-")
    if not normalized:
        raise ValueError("empty keycode")
    if normalized in KEYCODES:
        return KEYCODES[normalized]
    try:
        number = int(normalized, 0)
    except ValueError as exc:
        raise ValueError(f"unknown keycode {value!r}") from exc
    if not 0 <= number <= 0xFF:
        raise ValueError(f"keycode out of byte range: {value!r}")
    return number


def parse_media_usage(value: str) -> int:
    normalized = value.strip().lower().replace("_", "-")
    if not normalized:
        raise ValueError("empty media usage")
    if normalized in MEDIA_USAGES:
        return MEDIA_USAGES[normalized]
    try:
        number = int(normalized, 0)
    except ValueError as exc:
        raise ValueError(f"unknown media usage {value!r}") from exc
    if not 0 <= number <= 0xFFFF:
        raise ValueError(f"media usage out of word range: {value!r}")
    return number


def parse_modifier_token(value: str) -> int:
    return parse_byte_name(value, MODIFIER_TOKENS, "modifier token")


def keycode_name(code: int) -> str:
    for name in CANONICAL_NAMES:
        if KEYCODES[name] == code:
            return name
    for name, value in KEYCODES.items():
        if value == code:
            return name
    return f"0x{code:02x}"


def media_usage_name(code: int) -> str:
    for name, value in canonical_media_usages():
        if value == code:
            return name
    for name, value in MEDIA_USAGES.items():
        if value == code:
            return name
    return f"0x{code:04x}"


def modifier_token_name(token: int) -> str | None:
    return PREFERRED_MODIFIER_TOKEN_NAMES.get(token)


def token_name(token: int) -> str:
    modifier = modifier_token_name(token)
    if modifier is not None:
        return modifier
    return keycode_name(token)


def canonical_keycodes() -> list[tuple[str, int]]:
    return [(name, KEYCODES[name]) for name in CANONICAL_NAMES]


def vendor_basic_key_aliases() -> list[tuple[str, str, int]]:
    return [(label, alias, KEYCODES[alias]) for label, alias in VENDOR_BASIC_KEY_ALIASES]


def canonical_media_usages() -> list[tuple[str, int]]:
    names = (
        "fast-forward",
        "rewind",
        "play-pause",
        "stop",
        "eject",
        "previous-track",
        "next-track",
        "mute",
        "volume-up",
        "volume-down",
        "brightness-up",
        "brightness-down",
        "keyboard-brightness-up",
        "keyboard-brightness-down",
        "media-select",
        "email",
        "calculator",
        "my-computer",
        "internet-browser",
        "bass-up",
        "bass-down",
        "treble-up",
        "treble-down",
        "browser-search",
        "browser-home",
        "browser-back",
        "browser-forward",
        "browser-refresh",
        "vendor-0x0123",
    )
    return [(name, MEDIA_USAGES[name]) for name in names]
